<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCAZbXjF\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCAZbXjF/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCAZbXjF.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCAZbXjF\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerCAZbXjF\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'CAZbXjF',
    'container.build_id' => '889d7255',
    'container.build_time' => 1746794508,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCAZbXjF');
