<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmN534M\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmN534M/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmN534M.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmN534M\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerLmN534M\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'LmN534M',
    'container.build_id' => '042ecb8e',
    'container.build_time' => 1747140098,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmN534M');
