<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZMvCx0w\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZMvCx0w/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZMvCx0w.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZMvCx0w\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerZMvCx0w\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'ZMvCx0w',
    'container.build_id' => '3def1d59',
    'container.build_time' => 1747212786,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZMvCx0w');
