<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5io4WI1\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5io4WI1/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5io4WI1.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5io4WI1\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \Container5io4WI1\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => '5io4WI1',
    'container.build_id' => 'ba64a912',
    'container.build_time' => 1747128184,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5io4WI1');
