<?php

namespace ContainerOPPVxku;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserManagementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lJ8TfxL.App\Entity\UserManagement' shared service.
     *
     * @return \App\Entity\UserManagement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lJ8TfxL": it needs an instance of "App\\Entity\\UserManagement" but this type has been excluded in "config/services.yaml".');
    }
}
