<?php

namespace ContainerOPPVxku;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserManagementControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lJ8TfxL.App\Controller\UserManagementController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lJ8TfxL.App\\Controller\\UserManagementController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.lJ8TfxL.App\\Entity\\UserManagement', NULL, 'Cannot autowire service ".service_locator.lJ8TfxL": it needs an instance of "App\\Entity\\UserManagement" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\UserManagement',
            'em' => '?',
        ]))->withContext('App\\Controller\\UserManagementController::edit()', $container);
    }
}
