<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBzhuePr\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBzhuePr/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBzhuePr.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBzhuePr\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerBzhuePr\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'BzhuePr',
    'container.build_id' => '310d2eee',
    'container.build_time' => 1746763948,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBzhuePr');
