<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxmUgDq\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxmUgDq/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxmUgDq.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxmUgDq\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerSxmUgDq\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'SxmUgDq',
    'container.build_id' => '2384f63d',
    'container.build_time' => 1747314056,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxmUgDq');
