<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOGXBfw0\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOGXBfw0/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOGXBfw0.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOGXBfw0\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerOGXBfw0\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'OGXBfw0',
    'container.build_id' => 'a9246905',
    'container.build_time' => 1747228462,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOGXBfw0');
