<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW8txiUW\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW8txiUW/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerW8txiUW.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerW8txiUW\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerW8txiUW\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'W8txiUW',
    'container.build_id' => '881942a8',
    'container.build_time' => 1747284960,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW8txiUW');
