<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7c5GMDO\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7c5GMDO/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7c5GMDO.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7c5GMDO\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \Container7c5GMDO\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => '7c5GMDO',
    'container.build_id' => '0559b606',
    'container.build_time' => 1747025652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7c5GMDO');
