<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaPAvlL\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaPAvlL/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaPAvlL.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaPAvlL\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerIaPAvlL\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'IaPAvlL',
    'container.build_id' => 'a7af6716',
    'container.build_time' => 1747039558,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaPAvlL');
