<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRA4i1Tr\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRA4i1Tr/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRA4i1Tr.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRA4i1Tr\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerRA4i1Tr\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'RA4i1Tr',
    'container.build_id' => 'ab581c70',
    'container.build_time' => 1747056985,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRA4i1Tr');
