<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGidkm0W\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGidkm0W/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGidkm0W.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGidkm0W\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerGidkm0W\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'Gidkm0W',
    'container.build_id' => 'd0373087',
    'container.build_time' => 1747137429,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGidkm0W');
