<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEOOjx5S\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEOOjx5S/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEOOjx5S.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEOOjx5S\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerEOOjx5S\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'EOOjx5S',
    'container.build_id' => 'f616f570',
    'container.build_time' => 1747057260,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEOOjx5S');
