<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX52rxxE\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX52rxxE/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX52rxxE.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX52rxxE\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerX52rxxE\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'X52rxxE',
    'container.build_id' => '4525049e',
    'container.build_time' => 1747051031,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX52rxxE');
