<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4OcPswF\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4OcPswF/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/Container4OcPswF.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\Container4OcPswF\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \Container4OcPswF\Shopware_Core_KernelProdContainer([
    'container.build_hash' => '4OcPswF',
    'container.build_id' => '832faebf',
    'container.build_time' => 1746440640,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4OcPswF');
